const imageLetter = [
  {
    key: 1,
    imgSource: require("./source/apple.png"),
    value: "A",
    name: "Apple",
    sound: require("./source/A.mp3"),
  },
  {
    key: 2,
    imgSource: require("./source/bear.png"),
    value: "B",
    name: "Bear",
    sound: require("./source/B.mp3"),
  },
  {
    key: 3,
    imgSource: require("./source/cat.png"),
    value: "C",
    name: "Cat",
    sound: require("./source/C.mp3"),
  },
  {
    key: 4,
    imgSource: require("./source/dog.png"),
    value: "D",
    name: "Dog",
    sound: require("./source/D.mp3"),
  },
  {
    key: 5,
    imgSource: require("./source/egg.png"),
    value: "E",
    name: "Egg",
    sound: require("./source/E.mp3"),
  },
  {
    key: 6,
    imgSource: require("./source/fish.png"),
    value: "F",
    name: "Fish",
    sound: require("./source/F.mp3"),
  },
  {
    key: 7,
    imgSource: require("./source/giraffe.png"),
    value: "G",
    name: "Giraffe",
    sound: require("./source/G.mp3"),
  },
  {
    key: 8,
    imgSource: require("./source/house.png"),
    value: "H",
    name: "House",
    sound: require("./source/H.mp3"),
  },
  {
    key: 9,
    imgSource: require("./source/igloo.png"),
    value: "I",
    name: "Igloo",
    sound: require("./source/I.mp3"),
  },
  {
    key: 10,
    imgSource: require("./source/jug.png"),
    value: "J",
    name: "Jug",
    sound: require("./source/J.mp3"),
  },
  {
    key: 11,
    imgSource: require("./source/kangaroo.png"),
    value: "K",
    name: "Kangaroo",
    sound: require("./source/K.mp3"),
  },
  {
    key: 12,
    imgSource: require("./source/lollipop.png"),
    value: "L",
    name: "Lollipop",
    sound: require("./source/L.mp3"),
  },
  {
    key: 13,
    imgSource: require("./source/monster.png"),
    value: "M",
    name: "Monster",
    sound: require("./source/M.mp3"),
  },
  {
    key: 14,
    imgSource: require("./source/nest.png"),
    value: "N",
    name: "Nest",
    sound: require("./source/N.mp3"),
  },
  {
    key: 15,
    imgSource: require("./source/orange.png"),
    value: "O",
    name: "Orange",
    sound: require("./source/O.mp3"),
  },
  {
    key: 16,
    imgSource: require("./source/panda.png"),
    value: "P",
    name: "Panda",
    sound: require("./source/P.mp3"),
  },
  {
    key: 17,
    imgSource: require("./source/quail.png"),
    value: "Q",
    name: "Quail",
    sound: require("./source/Q.mp3"),
  },
  {
    key: 18,
    imgSource: require("./source/rainbow.png"),
    value: "R",
    name: "Rainbow",
    sound: require("./source/R.mp3"),
  },
  {
    key: 19,
    imgSource: require("./source/snake.png"),
    value: "S",
    name: "Snake",
    sound: require("./source/S.mp3"),
  },
  {
    key: 20,
    imgSource: require("./source/tiger.png"),
    value: "T",
    name: "Tiger",
    sound: require("./source/T.mp3"),
  },
  {
    key: 21,
    imgSource: require("./source/umbrella.png"),
    value: "U",
    name: "Umbrella",
    sound: require("./source/U.mp3"),
  },
  {
    key: 22,
    imgSource: require("./source/violin.png"),
    value: "V",
    name: "Violin",
    sound: require("./source/V.mp3"),
  },
  {
    key: 23,
    imgSource: require("./source/window.png"),
    value: "W",
    name: "Window",
    sound: require("./source/W.mp3"),
  },
  {
    key: 24,
    imgSource: require("./source/xylophone.png"),
    value: "X",
    name: "Xylophone",
    sound: require("./source/X.mp3"),
  },
  {
    key: 25,
    imgSource: require("./source/yoyo.png"),
    value: "Y",
    name: "Yoyo",
    sound: require("./source/Y.mp3"),
  },
  {
    key: 26,
    imgSource: require("./source/zigzag.png"),
    value: "Z",
    name: "Zigzag",
    sound: require("./source/Z.mp3"),
  },
  {
    key: 27,
    imgSource: require("./source/1.png"),
    value: "1",
    name: "One",
    sound: require("./source/1.mp3"),
  },
  {
    key: 28,
    imgSource: require("./source/2.png"),
    value: "2",
    name: "Two",
    sound: require("./source/2.mp3"),
  },
  {
    key: 29,
    imgSource: require("./source/3.png"),
    value: "3",
    name: "Three",
    sound: require("./source/3.mp3"),
  },
  {
    key: 30,
    imgSource: require("./source/4.png"),
    value: "4",
    name: "Four",
    sound: require("./source/4.mp3"),
  },
  {
    key: 31,
    imgSource: require("./source/5.png"),
    value: "5",
    name: "Five",
    sound: require("./source/5.mp3"),
  },
  {
    key: 32,
    imgSource: require("./source/6.png"),
    value: "6",
    name: "Six",
    sound: require("./source/6.mp3"),
  },
  {
    key: 33,
    imgSource: require("./source/7.png"),
    value: "7",
    name: "Seven",
    sound: require("./source/7.mp3"),
  },
  {
    key: 34,
    imgSource: require("./source/8.png"),
    value: "8",
    name: "Eight",
    sound: require("./source/8.mp3"),
  },
  {
    key: 35,
    imgSource: require("./source/9.png"),
    value: "9",
    name: "Nine",
    sound: require("./source/9.mp3"),
  },
  {
    key: 36,
    imgSource: require("./source/10.png"),
    value: "10",
    name: "Ten",
    sound: require("./source/10.mp3"),
  },
  {
    key: 37,
    imgSource: require("./source/0.png"),
    value: "0",
    name: "Zero",
    sound: require("./source/0.mp3"),
  },
];
export default imageLetter;
