const imageLetter = [
  {
    key: 1,
    imgSource: require("./source/apple.png"),
    value: "A",
    name: "Apple",
  },
  {
    key: 2,
    imgSource: require("./source/bear.png"),
    value: "B",
    name: "Bear",
  },
  {
    key: 3,
    imgSource: require("./source/cat.png"),
    value: "C",
    name: "Cat",
  },
  {
    key: 4,
    imgSource: require("./source/dog.png"),
    value: "D",
    name: "Dog",
  },
  {
    key: 5,
    imgSource: require("./source/egg.png"),
    value: "E",
    name: "Egg",
  },
  {
    key: 6,
    imgSource: require("./source/fish.png"),
    value: "F",
    name: "Fish",
  },
  {
    key: 7,
    imgSource: require("./source/giraffe.png"),
    value: "G",
    name: "Giraffe",
  },
  {
    key: 8,
    imgSource: require("./source/house.png"),
    value: "H",
    name: "House",
  },
  {
    key: 9,
    imgSource: require("./source/igloo.png"),
    value: "I",
    name: "Igloo",
  },
  {
    key: 10,
    imgSource: require("./source/jug.png"),
    value: "J",
    name: "Jug",
  },
  {
    key: 11,
    imgSource: require("./source/kangaroo.png"),
    value: "K",
    name: "Kangaroo",
  },
  {
    key: 12,
    imgSource: require("./source/lollipop.png"),
    value: "L",
    name: "Lollipop",
  },
  {
    key: 13,
    imgSource: require("./source/monster.png"),
    value: "M",
    name: "Monster",
  },
  {
    key: 14,
    imgSource: require("./source/nest.png"),
    value: "N",
    name: "Nest",
  },
  {
    key: 15,
    imgSource: require("./source/orange.png"),
    value: "O",
    name: "Orange",
  },
  {
    key: 16,
    imgSource: require("./source/panda.png"),
    value: "P",
    name: "Panda",
  },
  {
    key: 17,
    imgSource: require("./source/quail.png"),
    value: "Q",
    name: "Quail",
  },
  {
    key: 18,
    imgSource: require("./source/rainbow.png"),
    value: "R",
    name: "Rainbow",
  },
  {
    key: 19,
    imgSource: require("./source/snake.png"),
    value: "S",
    name: "Snake",
  },
  {
    key: 20,
    imgSource: require("./source/tiger.png"),
    value: "T",
    name: "Tiger",
  },
  {
    key: 21,
    imgSource: require("./source/umbrella.png"),
    value: "U",
    name: "Umbrella",
  },
  {
    key: 22,
    imgSource: require("./source/violin.png"),
    value: "V",
    name: "Violin",
  },
  {
    key: 23,
    imgSource: require("./source/window.png"),
    value: "W",
    name: "Window",
  },
  {
    key: 24,
    imgSource: require("./source/xylophone.png"),
    value: "X",
    name: "Xylophone",
  },
  {
    key: 25,
    imgSource: require("./source/yoyo.png"),
    value: "Y",
    name: "Yoyo",
  },
  {
    key: 26,
    imgSource: require("./source/zigzag.png"),
    value: "Z",
    name: "Zigzag",
  },
  {
    key: 27,
    imgSource: require("./source/1.png"),
    value: "1",
    name: "One",
  },
  {
    key: 28,
    imgSource: require("./source/2.png"),
    value: "2",
    name: "Two",
  },
  {
    key: 29,
    imgSource: require("./source/3.png"),
    value: "3",
    name: "Three",
  },
  {
    key: 30,
    imgSource: require("./source/4.png"),
    value: "4",
    name: "Four",
  },
  {
    key: 31,
    imgSource: require("./source/5.png"),
    value: "5",
    name: "Five",
  },
  {
    key: 32,
    imgSource: require("./source/6.png"),
    value: "6",
    name: "Six",
  },
  {
    key: 33,
    imgSource: require("./source/7.png"),
    value: "7",
    name: "Seven",
  },
  {
    key: 34,
    imgSource: require("./source/8.png"),
    value: "8",
    name: "Eight",
  },
  {
    key: 35,
    imgSource: require("./source/9.png"),
    value: "9",
    name: "Nine",
  },
  {
    key: 36,
    imgSource: require("./source/10.png"),
    value: "10",
    name: "Ten",
  },
  {
    key: 37,
    imgSource: require("./source/0.png"),
    value: "0",
    name: "Zero",
  },
];
export default imageLetter;
